import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import axios from "axios";
import { FiClock, FiImage, FiMapPin, FiMessageCircle, FiPhone } from "react-icons/fi";
import * as branchService from "@/services/branchService";
import type { Branch } from "@/types/branch";
const getErrorMessage=(e:unknown,f:string)=>axios.isAxiosError<{message?:string}>(e)?e.response?.data?.message||e.message||f:e instanceof Error?e.message:f;
const BranchesPage=()=>{const [branches,setBranches]=useState<Branch[]>([]);const [loading,setLoading]=useState(true);useEffect(()=>{branchService.getActiveBranches().then(r=>setBranches(r.branches)).catch(e=>toast.error(getErrorMessage(e,'Failed to load branches'))).finally(()=>setLoading(false))},[]);return <div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><div className="text-center"><h1 className="text-3xl font-bold text-secondary">Our Branches</h1><p className="mt-2 text-sm text-secondary/60">Find the branch nearest to you</p></div>{loading?<div className="mt-10 grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">{Array.from({length:3}).map((_,i)=><div key={i} className="animate-pulse overflow-hidden rounded-2xl border border-gray-100"><div className="h-44 bg-gray-100"/></div>)}</div>:branches.length===0?<div className="mt-10 flex h-60 flex-col items-center justify-center rounded-2xl border border-dashed border-gray-200"><FiMapPin className="text-3xl text-secondary/20"/><p className="mt-3 text-sm text-secondary/50">No branches available yet.</p></div>:<div className="mt-10 grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">{branches.map(b=><div key={b._id} className="overflow-hidden rounded-2xl border border-gray-100 bg-white shadow-sm hover:shadow-md"><div className="flex h-44 items-center justify-center overflow-hidden bg-gray-50">{b.images[0]?.url?<img src={b.images[0].url} alt={b.name} className="h-full w-full object-cover"/>:<FiImage className="text-3xl text-secondary/20"/>}</div><div className="p-5"><div className="flex items-start justify-between"><div><h3 className="font-semibold text-secondary">{b.name}</h3><p className="mt-0.5 flex items-center gap-1 text-xs text-secondary/50"><FiMapPin size={12}/>{b.locationName}</p></div>{b.isFeatured&&<span className="rounded-full bg-primary/10 px-2.5 py-1 text-xs font-medium text-primary">Featured</span>}</div><p className="mt-3 text-sm text-secondary/70">{b.address}</p><div className="mt-4 space-y-2 text-sm text-secondary/60">{b.phone&&<a href={`tel:${b.phone}`} className="flex items-center gap-2 hover:text-primary"><FiPhone size={14}/>{b.phone}</a>}{b.whatsapp&&<a href={`https://wa.me/${b.whatsapp.replace(/[^0-9]/g,'')}`} target="_blank" rel="noopener noreferrer" className="flex items-center gap-2 hover:text-primary"><FiMessageCircle size={14}/>WhatsApp</a>}{b.openingHours&&<p className="flex items-center gap-2"><FiClock size={14}/>{b.openingHours}</p>}</div>{b.googleMapEmbedUrl&&<div className="mt-4 overflow-hidden rounded-xl border border-gray-100"><iframe src={b.googleMapEmbedUrl} title={`${b.name} map`} width="100%" height="180" style={{border:0}} loading="lazy" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-scripts allow-same-origin allow-popups"/></div>}</div></div>)}</div>}</div>};
export default BranchesPage;
